package com.cope.core.constants

/**
 * @author Oscar Gallon on 2019-06-06.
 */
const val COROUTINE_IO_CONTEXT_PROVIDER = "COROUTINE_IO_CONTEXT_PROVIDER"
const val COROUTINE_COMPUTATIONAL_CONTEXT_PROVIDER = "COROUTINE_COMPUTATIONAL_CONTEXT_PROVIDER"
const val TIME_OUT_SECONDS = 30000.toLong()
const val BASE_URL = "http://94.237.29.193:3000"
const val TOKEN = "token"
const val BACKEND_DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
const val DATE_FORMAT = "MM/dd/yyyy"
const val DISPLAY_DATE_FORMAT = "MMM dd, yyyy"
const val FIREBASE_REMOTE_CONFIG_FEATURE_FLAG_HANDLER =
    "FIREBASE_REMOTE_CONFIG_FEATURE_FLAG_HANDLER"
const val FEATURE_FLAG_HANDLER =
    "FEATURE_FLAG_HANDLER"
const val LOGOUT_INTERACTOR = "LOGOUT_INTERACTOR"
