package com.cope.core

/**
 * @author Oscar Gallon on 2019-06-06.
 */
const val COROUTINE_IO_CONTEXT_PROVIDER = "COROUTINE_IO_CONTEXT_PROVIDER"
const val COROUTINE_COMPUTATIONAL_CONTEXT_PROVIDER = "COROUTINE_COMPUTATIONAL_CONTEXT_PROVIDER"
const val TIME_OUT_SECONDS = 30000.toLong()
const val BASE_URL = "http://172.16.8.108:3000"
